### ISSUE TITLE
[1.7.3] iPhone 5S / 8.4.1 - Watermark - Error message when user tries disable watermark on lomotif

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#115] opened 2016-02-18 12:19 UTC
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap on START button
3. Switch to Motif tab on Albums screen
4. Select any video
5. Select any music on Find Music screen
6. Tap Use 30 Seconds Preview under selected music
7. Enable Enter a Title field
8. Enter any title
9. Disable Watermark field

Expected result: Watermark disappears from lomotif and Watermark field is disabled

Actual result: Error message appears when user tries disable watermark on lomotif

Video: https://drive.google.com/file/d/0BwvEsBEA6ip4dXV1RjdvakRLa1E/view?usp=sharing

**Comment by xiuie** [comment] 2016-02-19 02:16
Thanks @vysohanych But as mentioned in the instructions, the watermark issue is not a bug as it will prompt the an in-app purchase once the build is live (has to link to the App Store).

**Comment by benchang** [comment] 2016-02-19 07:26
@xiuie you should have closed this!

**Closed as completed by benchang** 2016-02-19 07:26 UTC
Labels: Wont fix
