### ISSUE TITLE
[1.7.2] iPhone 6 / 9.2.1- My Music - Lists songs from Apple Music

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#107] opened 2016-02-13 19:14 UTC
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Select video (around 12 video clips)
3. Select “My Music”
4. Choose a song that you’ve saved to Apple’s Music (subscription service) but did not purchase
5. You’re prompted to download it from Cloud
6. Launch Apple Music App 
7. Download music to your device
8. Launch Lomotif
9. Select the downloaded song
10. Music fails to load (although cover art and title can be seen)

Expected Result: The music loads
Actual Result: No music/no waveform on Create screen

**Comment by benchang** [comment] 2016-02-15 12:30
duplicate of #102

**Closed as completed** 2016-02-17 06:07 UTC
Labels: Duplicate, Low (bug)
