### ISSUE TITLE
[1.9.16] iPhone 6S / 9.3.2 - Error message "Could not load preview..." is displayed on "Create" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#644] opened 2016-08-31 12:02 UTC
Frequency: 4/10

Action:
1: Launch the app.
2: Tap on "START" and search any motif on "Motif" tab.
3: Select few motifs and proceed to "Find Music" screen.
4: Tap on any music and immediately multiple taps on "Next" option.
5: Wait till the loading process over and user navigates to "Create" screen.
6: Check if error message "Could not load preview..." is displayed on "Create" screen.

Expected result: Preview should be displayed without error message.

 Actual result:
1: Error message "Could not load preview..." is displayed on "Create" screen.
2: Sometimes error message is displayed while loading process on "Find Music" screen.

Refer screenshot for more details.

**Comment by testershub** [comment] 2016-08-31 12:04
![error_create](https://cloud.githubusercontent.com/assets/18608449/18127968/24f0c784-6fa1-11e6-85cd-b431d065e5d7.jpg)

**Comment by hiteshbheda** [comment] 2016-08-31 19:43
@xiuie I can reproduce this issue on build [1.9.16] on iPhone 6 / iOS 9.3.5

Frequency: 2 / 10 (It's random issue. sometimes reproducible and sometimes not for the same song)

**Comment by vysohanych** [comment] 2016-08-31 22:41
@xiuie I can't reproduce this issue on build 1.9.16 on iPhone 5S / iOS 9.3.5

**Comment by hiteshbheda** [comment] 2016-12-11 06:00
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]

**Closed as completed** 2016-12-12 02:26 UTC
Labels: Low (bug), Reproducible
