### ISSUE TITLE
[1.7.4] iPhone 6/9.2- Create Add Music - Sound of video is start playing automatic on resume application.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#141] opened 2016-02-20 05:30 UTC
Frequency: Every time

Action: 
1. Tap on Start button.
2. Select any video with voice. 
3. Go next to Music..
4. Go next without selecting Music.
5. Check that you can hear sound of video on Create page.
6. Tap on Add Music icon and make sure there is no sound.
7. Minimize the application.
8. Resume the app and check sound.

Expected Result: Sound should not be started automatically.

Actual Result: Sound of video is started automatically on resume application.
[Auto play.zip](https://github.com/Lomotif/lomotif-ios-issues/files/139016/Auto.play.zip)

**Comment by xiuie** [comment] 2016-02-20 08:10
@Dipamit If I understand you correctly, this works as designed. When the app is relaunched, there is autoplay. @pmtheint For your info in case you have inputs.

**Comment by Dipamit** [comment] 2016-02-20 15:37
@xiuie : This is not work as designed. I checked with iPhone 5 IOS 8.3 On that phone its not auto play. If you go through video you get idea that video is auto play even though I am not on that page. This should be a problem. If this is work as design, then problem should be report for other device.

**Comment by benchang** [comment] 2016-02-20 18:28
I don't fully follow, @xiuie I'll let you decide whether this is a low priority bug, otherwise you should just close it.

**Comment by xiuie** [comment] 2016-02-26 08:26
@pmtheint leave it to you to decide whether:

video should be autoplayed on relaunch or not

**Comment by pmtheint** [comment] 2016-02-26 10:24
It's working as we designed. But I agree it should not be auto-playing on relaunch (mainly because that's how most apps function). Will keep a note on Asana.

**Comment by pmtheint** [comment] 2016-03-18 07:41
Logged and prioritised

**Closed as completed by pmtheint** 2016-03-18 07:41 UTC
Labels: Worked as design

**Comment by Dipamit** [comment] 2016-05-04 12:26
@xiuie : I am able to reproduce this issue on iPhone 5/9.3.1  But not able to reproduce on iPhone 5/8.3 

I think this problem is occur in IOS 9+ only.
