### ISSUE TITLE
[1.7.2] iPhone 6 / 9.2.1- Adjusting audio - App crashes

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#110] opened 2016-02-14 12:10 UTC
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Select screenshots (around 10 screenshots)
3. Select “My Music”
4. Turn on filters
5. Turn on stickers
6. Turn on titles
7. Move audio back and forth very quickly (waiting for it to start loading before changing again)
8. Do #7 around 10 times
9. App crashes

Expected Result: The music loads
Actual Result: App crashes

**Comment by tsukisa** [comment] 2016-02-15 06:57
@xiuie can't reproduce

**Comment by tsukisa** [comment] 2016-02-15 10:32
@xiuie fixed with commit Lomotif/lomotif-ios@08e8aa958c8e44881dd984a46f1c733df6efaadc

**Closed as completed** 2016-02-15 10:33 UTC
Labels: Critical (bug)
