### ISSUE TITLE
[2.1.4] iPhone 6S / 10.1.1 - User can Like lomotif without login - Search for any user -> open lomotif and click on Like

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1232] opened 2016-12-23 10:56 UTC
Frequency: Every time

Pre-requisite: User should be logged out from lomotif app

Action:
1. Launch the app
2. Tap on user search icon
3. Search for any user and open his/her profile
4. Tap on any existing lomotif to play it
5. During playing, click on Like (heart) symbol
6. Check whether user is able to like opened lomotif without login to app

Expected result: Without login, Like lomotif should not work

Actual result: Without login to lomotif app, any user can likes lomotif

**Comment by testershub** [comment] 2016-12-23 12:33
@xiuie Duplicate of #1196

**Closed as completed** 2016-12-23 13:07 UTC
Labels: Duplicate
