### ISSUE TITLE
[1.9.24] iPhone 6S / 10.0.1 - Black screen is displayed at preview when user change the time duration on "Create" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#731] opened 2016-09-22 06:45 UTC
Frequency: Every time

Action: 
1: Launch the app.
2: Tap on "START" and select 1 panorama image (Existing image).
3: Add any music and proceed to "Create" screen.
4: Observe preview is displayed for panorama image.
5: Apply sticker and filter on lomotif.
6: Export the lomotif.
7: Load recenlty exported lomotif.
8: Disable sticker and filter toggle button.
9: Change the time duration to 30 secs.
10: Check if black screen is displayed at preview.

Expected result: Preview should be displayed with changed time duration.

Actual result: Black screen is displayed at preview when user change the time duration on "Create" screen.

**Comment by testershub** [comment] 2016-09-22 06:54
Refer following video for more details:
http://www.screencast.com/t/8rUIRowp3Fo

**Comment by xiuie** [comment] 2016-09-22 09:57
@testershub I can recreate it with an ADDITIONAL step which is to "Return to Home > Launch Project" on my iPhone 6/10.0

**Comment by Dipamit** [comment] 2016-09-22 10:31
@xiu: I am able to reproduce this issue on iPhone 5/9.3.4 for build 1.9.24

Note: When project creating with Panorama image, it displayed black frame for preview.
1. Export this project without following steps 5 to 9, Error 11841 generated.
2. Export this project with following steps 5 to 9, Application block. Need to restart app.

**Comment by hiteshbheda** [comment] 2016-12-11 06:08
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]

**Comment by testershub** [comment] 2016-12-12 05:31
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1 and iPhone 6S / 10.0.2.

**Closed as completed** 2016-12-12 06:28 UTC
Labels: High (bug), Reproducible
