### ISSUE TITLE
[1.7.12] iPhone 6 / iOS 9.2 - Create - Lomotif saved changes even though tap on No.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#255] opened 2016-03-27 19:34 UTC
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button and choose more than 1 video/ images.
3. Save Lomotif with multiple items.
4. Open created Lomotif.
5. Remove 2-3 items using - and tap on Home button.
6. It will ask to save, tap on NO from message.
7. Open Lomotif again.

Expected result: It should display back items as user did not save changes made.

Actual result: Deleted videos/ images are not displayed even though tap on No while it ask to save.
[Video Saved Even though tap No.zip](https://github.com/Lomotif/lomotif-ios-issues/files/191069/Video.Saved.Even.though.tap.No.zip)

**Comment by hiteshbheda** [comment] 2016-03-28 18:46
@xiuie @tsukisa I can replicate this on iPhone 6 / iOS 9.3

**Comment by tsukisa** [comment] 2016-04-01 09:54
Duplicate of #125

**Closed as completed by tsukisa** 2016-04-01 09:54 UTC
Labels: Low (bug)
