### ISSUE TITLE
[1.8.14] iPhone 6 / iOS 9.3.1 - Unexpected Behavior at My Music - Change song in existing lomotif and select song from My Music

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#386] opened 2016-05-13 15:07 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Open any existing lomotif
3. Click on Change song icon
4. Tap on My Music tab on Find Music screen
5. Indexing characters available at Right side of the songs
6. Click on any character from index list (I have clicked on  "K")
7. Respective songs will be available on the screen
8. Click on any song from the list

Expected result: By just clicking on song song should not be added from My Music without pressing Apply button at Top Right corner

Actual result: Song added without clicking on Apply button

![img_2203](https://cloud.githubusercontent.com/assets/9691390/15252212/6fad8cc4-194a-11e6-9b71-57e1d8e475d4.PNG)

![img_2204](https://cloud.githubusercontent.com/assets/9691390/15252211/6fad272a-194a-11e6-87ba-f94b15085792.PNG)

![img_2205](https://cloud.githubusercontent.com/assets/9691390/15252213/6fb0aa1c-194a-11e6-9d90-8de3b635e5a9.PNG)

![img_2206](https://cloud.githubusercontent.com/assets/9691390/15252210/6faceb0c-194a-11e6-8beb-9b821eb90bce.PNG)

**Comment by vysohanych** [comment] 2016-05-15 10:36
I can't reproduce it on build 1.8.15 on iPhone 5S iOS 8.4.1.

**Comment by tsukisa** [comment] 2016-05-19 23:59
fixed with commit Lomotif/lomotif-ios@50a1c251e728d4a0a04df7e3f400ef5d794821f5

**Closed as completed by tsukisa** 2016-05-19 23:59 UTC
Labels: Low (bug)
