### ISSUE TITLE
[1.9.3] iPhone 6 / iOS 9.3.3 - Instagram folder automatically expands - Click on Instagram folder and click on back ->Scroll down and scroll up again

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#525] opened 2016-07-26 14:53 UTC
Frequency: Every time

**_Pre-requisite: Don't link (Unlink) your Instagram account_**

Action:
1. Launch Lomotif
2. Tap on Start
3. On Albums screen, click on Instagram folder
4. Without entering Username and Password click on back button from Top Left corner
5. Now, on the Albums screen, drag the screen upside (scroll down the screen)
6. Again, drag the screen down wards (scroll up the screen)
7. Check whether Instagram folder has expanded or not

Expected result: Instagram folder should not be expanded

Actual result: Instagram folder is expanded without taping it

**Comment by vysohanych** [comment] 2016-07-26 15:01
Duplicate of #195

**Comment by testershub** [comment] 2016-07-28 06:59
I can reproduced this issue for build [1.9.0 (1.9.4)] on iPhone 6S /9.3.2, iPad Mini 3/9.3.2

**Comment by hiteshbheda** [comment] 2016-08-04 10:27
@xiuie I can't reproduce this issue for build [1.9.7] on iPhone 6 / iOS 9.3.3

**Comment by testershub** [comment] 2016-08-06 14:08
@xiuie Issue is resolved on latest build [1.9.9].

**Comment by hiteshbheda** [comment] 2016-08-06 15:54
@xiuie I can't reproduce this issue for build [1.9.9] on iPhone 6 / iOS 9.3.4

**Closed as completed** 2016-08-07 09:38 UTC
Labels: Reproducible
