### ISSUE TITLE
[1.7.2] iPhone 6 / 9.2.1- Motifs Page - Clips populated in the wrong album

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#111] opened 2016-02-17 03:42 UTC
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Hit Start
3. Tap Motifs tab
4. Open albums to browse without selecting (scroll down to access different albums)
5. On ~4th album open, contents will wrong

Expected Result: Clips should match album
Actual Result: Clips do not match album title

See below: Contents are Nicki Minaj but title is Justin Bieber

![slack for ios upload-15 png](https://cloud.githubusercontent.com/assets/16533289/13099276/b8ecf550-d56b-11e5-8a02-acbb12ab0d77.jpeg)

**Comment by tsukisa** [comment] 2016-02-17 06:06
Duplicate of #96

**Closed as completed by tsukisa** 2016-02-17 06:06 UTC
Labels: Duplicate, High (bug)
