### ISSUE TITLE
[1.8.6] iPad Air/IOS 9.3.1- Adjust Tab- Thumbnail for adjusting time duration is going out of the time line  in minimum and maximum limit.

### ISSUE THREAD

**Issue by 87Swati** [Lomotif/lomotif-ios-issues#300] opened 2016-04-18 12:02 UTC
Frequency: Every Time

Steps to Reproduce:
1.Create a project with the minimum(3 sec)  or max time(30 sec) limit in adjust tab.
2.Save the project.
3.Again open the project and play the project.
4.click on the adjust tab and view the thumbnail position.

Actual Result: Thumbnail is displaying out of the time line in both the cases(minimum and maximum)

Expected Result:  Thumbnail should be on the timeline .
![img_0599](https://cloud.githubusercontent.com/assets/17292514/14603420/c733c206-056d-11e6-84c3-cf03dc7b8a11.png)
![img_0595](https://cloud.githubusercontent.com/assets/17292514/14603449/feb2b8b8-056d-11e6-854e-9f6bc58d4340.png)

**Comment by Dipamit** [comment] 2016-04-18 13:10
Able to reproduce this issue on iPhone 5/8.3 for build [1.8.6]

**Comment by hiteshbheda** [comment] 2016-04-18 15:00
@xiuie I can reproduce this issue for build [1.8.6] on iPhone 6 / iOS 9.3.1

**Comment by tsukisa** [comment] 2016-04-18 16:46
duplicate of #275

**Closed as completed by tsukisa** 2016-04-18 16:46 UTC
