### ISSUE TITLE
[1.8.32] iPad mini / iOS 8.3 - Create - Application crashes after adding song from My Music tab

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#474] opened 2016-06-08 14:53 UTC
Frequency: Every Time

Action:
1. Open the application
2. Tap START button on the home screen
3. Add some motifs on the Albums screen
4. Tap apply button on the Albums screen
5. Switch to the My Music tab on 
6. Tap on Menu button of My Music tab
7. Select Artists category
8. Select any song from Artists category
9. Tap apply button on the Find Music screen
10. Tap change song icon on Create screen
11. Repeat 5-9 steps and wait

Expected result: Application works as expected

Actual result: Application crashes

Video: [Recording #57.mp4.zip](https://github.com/Lomotif/lomotif-ios-issues/files/305031/Recording.57.mp4.zip)

Crash log: [crash_log.txt.zip](https://github.com/Lomotif/lomotif-ios-issues/files/305032/crash_log.txt.zip)

**Comment by hiteshbheda** [comment] 2016-06-08 15:06
@xiuie Duplicate of #470

**Comment by vysohanych** [comment] 2016-06-12 08:03
I can't reproduce it on build 1.8.33 on iPhone 5S iOS 8.4.1

**Comment by hiteshbheda** [comment] 2016-06-13 07:20
@xiuie I can't reproduce this issue for build 1.8.33 on iPhone 6 / iOS 9.3.2

**Closed as completed** 2016-06-13 07:25 UTC
Labels: Help Wanted
