### ISSUE TITLE
[1.7.3] iPhone 5S / 8.4.1 - Find Music - All music does not appear when user cancels searching

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#114] opened 2016-02-18 12:01 UTC
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap on START button
3. Switch to Motif tab on Albums screen
4. Select any video
5. Tap Apply button
6. Enter search text 'guts' on Find Music screen and tap search button
7. Cancel searching on Find Music screen

Expected result: All music appears on Find Music screen

Actual result: User sees the same music as after searching
[cancel_search.zip](https://github.com/Lomotif/lomotif-ios-issues/files/136128/cancel_search.zip)

**Comment by Dipamit** [comment] 2016-02-20 15:53
Able to reproduce this issue. Tested with iPhone 6 iOS 9.2

**Comment by vysohanych** [comment] 2016-04-15 10:40
I can reproduce it on build 1.8.5 on iPad 2 iOS 9.3.1

**Comment by vysohanych** [comment] 2016-04-17 08:35
This bug seems is duplicate of bug #155  . You can close one of them.

**Comment by hiteshbheda** [comment] 2016-04-18 10:37
@xiuie @tsukisa Duplicate of #155

**Closed as completed** 2016-04-26 19:55 UTC
Labels: Low (bug)
