### ISSUE TITLE
[1.9.48] iPhone 6 / 10.1.1- "Invalid Email format" Error - Change Email and provide valid Email

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1035] opened 2016-11-30 17:08 UTC
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials
3. Go to User profile information page
4. Click on Email field to change Email
5. On next screen, enter valid Email address
6. Check whether user is able to change Email or not

Expected result: User should be able to change Email

Actual result: Error message "Invalid Email format" display

![email](https://cloud.githubusercontent.com/assets/9691390/20762823/b6a25550-b74d-11e6-8c05-301f13f3d720.PNG)

**Comment by testershub** [comment] 2016-12-01 05:37
@xiuie Duplicate of #971

**Comment by hiteshbheda** [comment] 2016-12-09 15:15
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]

**Closed as completed** 2016-12-10 09:04 UTC
