### ISSUE TITLE
[1.9.53]  - User doesn't received "Reset Password" link on registered email.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1101] opened 2016-12-07 12:52 UTC
Frequency: Every time

Action:
1: Launch the app and navigate to "Sign Up" screen.
2: Enter valid email and password.
3: Tap on "Sign Up" button.
4: Enter valid username and remove email.
5: Tap on "Let's Go" button.
6: Navigate to "Settings >> Email"  and enter valid email  id and save it.
7: Logout form the account and tap on "Forgot Password?" option.
8: Enter recently entered email (In step  - 6) and tap on "Recover" button.
9: Navigate to registered email account.
10: Check if user is received "Reset Password" link.

Expected result: User should receive "Reset Password" link on registered email id with confirmation email.  

Actual result: 
1: User doesn't received "Reset Password" link on registered email.
2: User is receiving "Confirmation email" when user sent recover password request.

**Comment by Pankaj-Testershub** [comment] 2016-12-07 13:11
@xiuie I can reproduce this issue for build [1.9.53].
User is receiving "Confirmation email" when user sent recover password request and not the "Reset password" link.

**Comment by hiteshbheda** [comment] 2016-12-07 14:13
@xiuie I can't reproduce this issue for build [1.9.53] on iPhone 6 / iOS 10.1.1

Works properly.

**@testershub @xiuie  When user proceed for Forget password, it send "Confirmation Email" and once user will click on "Confirm email address" button, then it will send "Password Reset" link to updated email address.**

**Comment by xiuie** [comment] 2016-12-07 16:13
@testershub @Pankaj-Testershub Hitesh sounds correct, I will close this bug for now. If you don't get reset please tell me to reopen.

**Closed as completed by xiuie** 2016-12-07 16:13 UTC
Labels: Worked as design
