### ISSUE TITLE
[1.6.5] App crashed when toggle ON/OFF Enter A Title

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#18] opened 2016-01-12 09:33 UTC
1. Open the app
2. Tap on "Create a Lomotif"
3. Tap on "Motifs" > Tap on any video > Tap on "Tick" on the top right
4. It will open the page as "Find Music" 
5. Tap on Available video > Tap on "Use 30 seconds Preview" 
6. It will open "Create" page
7. Enter a Title - Toggle ON/OFF 
8. Observe'

**Comment by tsukisa** [comment] 2016-01-12 10:21
Bug resolved with commit at Lomotif/lomotif-ios@73b35be9d9ca19f42003feff80e2b4abc815bc8b

**Comment by tsukisa** [comment] 2016-01-15 05:24
@xiuie I can't replicate on my side

**Comment by tsukisa** [comment] 2016-02-15 07:01
Duplicate of #84

**Closed as completed by tsukisa** 2016-02-15 07:01 UTC
Labels: Critical (bug)
