### ISSUE TITLE
[1.7.10] iPhone 5/ 8.3 - Application crash on tapping selected video.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#241] opened 2016-03-23 13:41 UTC
Frequency : Every time

Action:
1. Open application and tap on any created Lomotif video.
2. Tap on any playing video next to add album  while running video.

Expected result: It should jumps to selected video.

Actual result: Application crash.

**Comment by xiuie** [comment] 2016-03-23 19:09
@tsukisa Ben and I can replicate this some time.. And Ben suspects this is what is causing the most problems (related to the music loop)

**Comment by tsukisa** [comment] 2016-03-24 05:26
@xiuie is this lomotif project crash?

**Comment by xiuie** [comment] 2016-03-24 06:08
Yes!

Loh Xiu Hui  
Co-Founder, Lomotif
Mobile: +65 96863007
Email: xiu@lomotif.com
Website: www.lomotif.com

**Comment by tsukisa** [comment] 2016-03-24 06:12
Duplicate of #235
The issue is caused by opening a project that contains a song

**Closed as completed by tsukisa** 2016-03-24 06:12 UTC
Labels: Critical (bug)
