### ISSUE TITLE
[1.8.8] iPad 2 / iOS 9.3.1 - Create - Title doesn't appear on the video

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#339] opened 2016-04-22 17:33 UTC
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Select a few motifs
5. Tap apply button on the Albums screen
6. Tap apply button on the Find Music screen and tap OK button on the Cancel dialog
7. Expand 'Enter A Title' field and enter the title

Expected result: Title should appear on the video

Actual result: Title doesn't appear on the video

![img_0347](https://cloud.githubusercontent.com/assets/3593359/14749655/66fb53fe-08c9-11e6-85dd-f4bc649cc114.jpg)

**Comment by tsukisa** [comment] 2016-04-22 17:34
duplicate of #333

**Closed as completed by tsukisa** 2016-04-22 17:34 UTC
Labels: Duplicate
