### ISSUE TITLE
[1.8.12] iPhone 5c / iOS 9.3.1 - Alignment of My Music page get disturbed when menu is open and user scroll down and then scroll up

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#375] opened 2016-05-05 10:55 UTC
Frequency: Every time

Action:
1. Launch Lomotif.
2. Tap on Start.
3. Select few images from Camera Roll.
4. Click on Apply button at Top Right corner.
5. Click on My Music tab.
6. Click on Menu button on the left.
7. Scroll down the page.
8. Now scroll up the page.

Actual result: There are overlapping issues. Please see screenshot for more information - http://prntscr.com/b0im2e

Expected result: There shouldn't be any overlapping.

**Comment by hiteshbheda** [comment] 2016-05-05 15:00
@xiuie Duplicate of #217

**Closed as completed** 2016-05-05 16:45 UTC
Labels: Duplicate
