### ISSUE TITLE
[1.8.14] iPhone 6 / iOS 9.3.1 - Application Crash - Clicking on Message, WhatsApp and Email at same time at Export screen

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#391] opened 2016-05-13 18:49 UTC
Frequency: Some times

Action:
1. Launch Lomotif
2. Open any existing lomotif
3. Click on Export button at Top Right Corner
4. Click on Message, WhatsApp and Email at same time

Expected result: Lomotif should be exported on any media on Message, WhatsApp or on Email

Actual result: Application crash

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UZVA3X1N4NWhvSjQ)

**Comment by xiuie** [comment] 2016-05-14 05:42
@hiteshbheda Isn't this a duplicate of a previous bug? And we said that the fix will be to only allow one share button to be activated at a time?

**Closed as completed by xiuie** 2016-05-14 05:42 UTC

**Comment by hiteshbheda** [comment] 2016-05-14 06:23
@xiuie Yes, it looks same but i think previously media sharing were occurring instead of crashing app.

**And specially, for this issue when we click on cancel for WhatsApp, it crashes.**

**Comment by hiteshbheda** [comment] 2016-05-18 19:07
@xiuie @tsukisa I can reproduce this issue again for build [1.8.19] on iPhone 6 / iOS 9.3.1

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UQlVFUmstYTFtakU)

**Comment by hiteshbheda** [comment] 2016-05-22 12:48
@xiuie @tsukisa I can still reproduce this issue for build [1.8.23] on iPhone 6 / iOS 9.3.2 almost every time
