### ISSUE TITLE
[1.8.9] iPhone 6 / iOS 9.3.1 - Stickers not loading - Create lomotif with stickers tab, Stickers not loading and displaying on the screen

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#353] opened 2016-04-25 04:25 UTC
Frequency: Most of the time

Action:
1. Launch Lomotif
2. Tap on start
3. Select few videos from camera roll
4. Click on apply button from top right corner
5. Tap on Find Music tab from Find Music screen
6. Click on any song from the list and click on apply button
7. Click on Stickers tab and Enable it
8. Observe the available stickers

Expected result: Stickers should be loaded once Sticker tab is enabled and selected sticker should be displayed on the playing screen

Actual result: Stickers not loaded in stickers tab and even i have enabled sticker button but sticker is not displaying on the playing screen

[Stickers loading Bug Image](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UUU9IRnNjVElXVUE)

**Comment by hiteshbheda** [comment] 2016-04-25 05:35
@xiuie I can't replicate it now. I think it was a sticker / app updating time and i have tried the steps at that time.

**Comment by Dipamit** [comment] 2016-04-25 12:17
Not able to reproduce this issue on iPhone 5/8.3 for build [1.8.9]

**Comment by vysohanych** [comment] 2016-04-25 21:59
I can't reproduce it on build v1.8.2 (1.8.10) on iPhone 5S iOS 8.4.1

**Comment by xiuie** [comment] 2016-04-25 22:39
Would stickers be down during app updating @ruiwen ?

**Comment by ruiwen** [comment] 2016-04-25 23:55
No they shouldn't be completely unavailable even over an update, particularly if they were loaded before.

@hiteshbheda Did this happen on a fresh install? Or did the stickers load before?

**Comment by hiteshbheda** [comment] 2016-04-26 04:56
@xiuie @ruiwen No, It doesn't happen on build [1.8.10]. Even it was happening for about an hour when i have logged this issue here then it automatically resolved.

**Comment by ruiwen** [comment] 2016-04-26 19:26
@hiteshbheda @Dipamit @vysohanych Thanks guys, but I'll have to close this for now seeing as we can't reliably replicate. Feel free to open a new issue if it occurs again and we know reliably when it happens?

/cc @xiuie

**Closed as completed by ruiwen** 2016-04-26 19:26 UTC
Labels: Help Wanted
