### ISSUE TITLE
[2.1.3] iPhone 6 Plus / 10.1.1 - User is receiving two notifications when user left lomotif unfinished on "Create" screen. 

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1188] opened 2016-12-21 06:26 UTC
Frequency- Everytime

Action:
1: Launch the app.
2: Navigate to "Home" screen.
3: Create lomotif with few motifs.
4: Tap on device "Home(Hard) key".
5: Check if user receives two notifications.

Expected result: User should receive only one notification for unfinished lomotif on "Create" screen.

Actual result: User is receiving two notifications when user left lomotif unfinished on "Create" screen.

Please refer video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudZTItbS1mVFNSWmM

**Comment by testershub** [comment] 2016-12-21 08:20
@xiuie Duplicate of #1007

**Closed as completed** 2016-12-21 12:36 UTC
Labels: Duplicate
