### ISSUE TITLE
[1.8.20] iPhone 6 / iOS 9.3.2 - Motifs / Videos repeated in Instagram and other Folders  - Open Instagram and other folders then close and open the same folder again will make double no. of motifs / videos

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#429] opened 2016-05-20 09:26 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Open Instagram folder
3. There are 2 motifs / videos available in the folder now (No. of motifs / videos may be differ in your devices)
4. Close the Instagram folder 
5. Open the Instagram folder again
6. Check the number of videos are increased by 2 (In your device instead of 2 it will be increased available no. of videos count)
7. Again close the folder and open it again
8. It will increase 2 more videos (repeat videos)

Expected result: Number of videos should not be increase by reopen Instagram folder again

Actual result: Every time Reopening Instagram folder will add 2 videos (Repeat the videos in the folder)

**Important Note: This issue applicable for all folders like Slo-mo, Time-lapse, Boomerang, Instagram, Lomotif, iCloud folder**

Important Note: This issue applicable for all folders like Slo-mo, Time-lapse, Boomerang, Instagram, Lomotif, iCloud folder

![img_2371](https://cloud.githubusercontent.com/assets/9691390/15423418/fce3045c-1e9a-11e6-8ead-40bdfd2d082c.PNG)

![img_2372](https://cloud.githubusercontent.com/assets/9691390/15423416/fc6c33e0-1e9a-11e6-8ac9-940160df978e.PNG)

![img_2373](https://cloud.githubusercontent.com/assets/9691390/15423417/fc6e62b4-1e9a-11e6-900a-c38065156ab2.PNG)

**Comment by pallavipillai** [comment] 2016-05-20 11:39
The issue is reproducible on build [1.8.20] iPAD 3/iOS 9.3.2

**Comment by tsukisa** [comment] 2016-05-20 18:23
fixed with commit Lomotif-lomotif-ios@b7b9ae46d215c7b0af0a9f685620939cb88f97f6

**Closed as completed by tsukisa** 2016-05-20 18:23 UTC
