### ISSUE TITLE
[1.8.6] iPad 2 / iOS 9.3.1 - Setting - Application crashes if user taps on any linked account when network is unavailable

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#282] opened 2016-04-17 14:06 UTC
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap settings button on the nome screen
3. Tap Linked Accounts button on the Settings screen
4. Log in into all social networks
5. Close the application
6. Turn off wi-fi
7. Launch Lomotif
8. Tap settings button on the nome screen
9. Tap Linked Accounts button on the Settings screen
10. Tap on any social nework button

Expected result: User sees error message that network is unavailable

Actual result: Application crashes

Video: [Recording #17.zip](https://github.com/Lomotif/lomotif-ios-issues/files/222661/Recording.17.zip)

Crash log: [Lomotif-2016-04-17-163718.zip](https://github.com/Lomotif/lomotif-ios-issues/files/222662/Lomotif-2016-04-17-163718.zip)

**Comment by hiteshbheda** [comment] 2016-04-17 17:08
@xiuie @tsukisa I can't reproduce this bug for build [1.8.6] on iPhone 6 / iOS 9.3.1

**Comment by Dipamit** [comment] 2016-04-18 10:58
I am not able to reproduce this issue on iPhone 5/8.3 for build [1.8.6]

**Comment by tsukisa** [comment] 2016-04-20 21:46
duplicate of #245

**Closed as completed by tsukisa** 2016-04-20 21:46 UTC
Labels: High (bug)
