### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2.1 - App crash - During Searching motifs

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#204] opened 2016-03-07 16:00 UTC
Frequency: Twice

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Motif tab on Albums screen
4. Tap on Search box.
5. Type word "nicki minaj"
6. Click on Search button

Expected result: Results / motifs related to "nicki minaj" word should be displayed

Actual result: Application Crash

**Comment by xiuie** [comment] 2016-03-12 02:30
@hiteshbheda It happened to me too. But try to see if you can find out how to replicate this one 100% if you have spare time..

**Comment by hiteshbheda** [comment] 2016-03-12 05:48
@xiuie I am unable to replicate it now. But still when i'm trying to search results for "nicki minaj" and when i scroll down to load more motifs, it crashes everytime.

**Comment by tsukisa** [comment] 2016-03-18 13:16
Duplicate of #209 
two words search crash issue has been resolved

**Closed as completed by tsukisa** 2016-03-18 13:16 UTC
Labels: Duplicate, High (bug)
