### ISSUE TITLE
[1.8.20] iPhone 6 / iOS 9.3.2 - Song Overlapping - Create lomotif with images/ motifs and audio and play it multiple times

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#427] opened 2016-05-20 08:15 UTC
Frequency: Every times

Action:
1. Launch Lomotif
2. Click on Start button
3. Select 2-3 motifs from any Motif category or select 2-3 images from Camera Roll
4. Click on Apply button at Top Right corner
5. Add any song from Find music or My Music tab
6. Click on Apply from Top Right corner
7. Now play created lomotif till end.
8. Once lomotif completely played, Play it again by tapping on "Play" button on the screen
9. Check whether song plays clearly or it's overlapping

Expected result: Lomotif should be played with clear sound withput any overlapping audio

Actual result: Playing lomotif second time, third time or multiple times create sound overlapping / Audio not clear

**Comment by pallavipillai** [comment] 2016-05-20 09:38
The issue is reproducible on build [1.8.20]  on iPad 3 / iOS 9.3.2

**Comment by vysohanych** [comment] 2016-05-20 09:45
I can reproduce it on build 1.8.20 on iPad mini 2 iOS 9.3.1.

**Comment by tsukisa** [comment] 2016-05-20 18:25
fixed with commit lomotif/lomotif-ios@0864757edfff50954d329c672138f8c1e7ab23be

**Closed as completed by tsukisa** 2016-05-20 18:25 UTC
Labels: Critical (bug)
