### ISSUE TITLE
[1.8.15] iPhone 6 / iOS 9.2.1 - Neverending "Loading song" dialogue

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#401] opened 2016-05-15 06:08 UTC
Frequency
1. Select Start
2. Select any clip
3. Select any song from my music
4. Close project and save
5. Open saved project (with a song from "My Music")

Expected result: Music loads
Actual: Never ending "Loading Song" Nothing will respond except the "Export" and "Home"

**Comment by hiteshbheda** [comment] 2016-05-15 06:59
@xiuie @tsukisa I can replicate this issue for build [1.8.15] on iPhone 6 / iOS 9.3.1 Every time

**Comment by vysohanych** [comment] 2016-05-15 11:47
I can't reproduce it on build 1.8.15 on iPhone 5S iOS 8.4.1. because the application crashes when I try to add any song from My Music tab

**Comment by Dipamit** [comment] 2016-05-15 13:14
I am able to reproduce this issue on iPhone 5/8.3 for build [1.8.15]

**Comment by pallavipillai** [comment] 2016-05-15 17:08
I can reproduce the issue on iPad 3/9.3.1 for build [1.8.15]. When user opens any saved project, loading sign never ends.

**Comment by tsukisa** [comment] 2016-05-16 01:29
fixed with commit Lomotif/lomotif-ios@22482c7021bae236733ac80040c42b6bf949b4b9

**Closed as completed by tsukisa** 2016-05-16 01:29 UTC
Labels: Critical (bug)

**Comment by hiteshbheda** [comment] 2016-05-16 18:02
@xiuie @tsukisa I can't reproduce this issue for build [1.8.16] on iPhone 6 / iOS 9.3.1.
