### ISSUE TITLE
[2.1.2] iPhone 6S / 10.1.1 - "dump" popup error - Navigate to Media screen from Home screen

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1144] opened 2016-12-19 04:34 UTC
Frequency: Everytime

Action:
1. Launch the app
2. Tap on Media icon on home screen or Slide Home screen from Left to Right
3. Check on the media screen any "dump" error popup display or not

Expected result: "dump" Error popup should not be displayed on media screen

Actual result: User user navigates from Home to Media screen, "dump" error popup is displayed

![img_0993](https://cloud.githubusercontent.com/assets/9691390/21301326/8d7aafa4-c5d2-11e6-97f1-1cbfc2ff1569.PNG)

**Comment by Pankaj-Testershub** [comment] 2016-12-19 06:23
@xiuie Duplicate of #1117.

**Comment by xiuie** [comment] 2016-12-19 06:33
Please ignore this screen. This is only for testing purposes.

**Closed as completed by xiuie** 2016-12-19 06:33 UTC
