### ISSUE TITLE
[1.6.5] iPad mini/ 8.4 - Images are not displaying on "find music" page after scrolling the page.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#30] opened 2016-01-14 14:28 UTC
Frequency: Always

Action:
1. Launch the app.
2. Tap on start.
3. Tap on camera Roll.
4. Select any one file from camera roll and tap on ok(v) sign.
5. Files loading are displaying at 'Find Music' section.
6. Scroll the page.
7. Check whether Images are not displaying on "find music" page after scrolling the page or not.

Expected Result: Images should display after scrolling "find music" page.

Actual Result: Images are not displaying on "find music" page after scrolling the page.

Screenshot: http://prntscr.com/9q03mj

**Comment by tsukisa** [comment] 2016-01-15 05:17
Duplicate of #4

**Closed as completed** 2016-01-15 07:47 UTC
Labels: Duplicate
