### ISSUE TITLE
[1.8.20] iPhone 6 / iOS 9.3.2 - Application Crash - Click on Facebook or Instagram folder from Camera Roll

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#426] opened 2016-05-20 08:00 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Click on Start button
3. Click on Facebook folder or Instagram folder or both the folder at same time
4. Check whether application crashes or not

Expected result: Clicked Facebook folder or Instagram folder should be opened

Actual result: Application crash

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4URmlMQ2FUSkxWQlk)

![img_2359](https://cloud.githubusercontent.com/assets/9691390/15420855/a56e1a44-1e8c-11e6-8e91-1f45a77ba9e8.PNG)

**Comment by vysohanych** [comment] 2016-05-20 09:44
I can't reproduce it on build 1.8.20 on iPad mini 2 iOS 9.3.1.

**Comment by xiuie** [comment] 2016-05-20 18:24
I can reproduce this on iPhone 6 / 1.9.2

**Comment by tsukisa** [comment] 2016-05-20 18:26
fixed with commit Lomotif/lomotif-ios@b7b9ae46d215c7b0af0a9f685620939cb88f97f6

**Closed as completed by tsukisa** 2016-05-20 18:26 UTC
Labels: Critical (bug)
