### ISSUE TITLE
[1.8.6] iphone 5s/iso 9.3 - On battery pecentage 26% application is still crashing.

### ISSUE THREAD

**Issue by garimaojha** [Lomotif/lomotif-ios-issues#291] opened 2016-04-17 19:06 UTC
1.Open the app.
2.Click on start
3.Select video.
4. Add music
5.Application start crashing.

Frequency: Always.

**Comment by garimaojha** [comment] 2016-04-17 19:13
Please find the attached screen . My battery percentage is 30% and app is still crashing.
![img_0876](https://cloud.githubusercontent.com/assets/18511322/14589386/7b1797a4-04fe-11e6-964b-20416678e17a.PNG)

**Comment by xiuie** [comment] 2016-04-18 01:16
Duplicate of #289

**Comment by hiteshbheda** [comment] 2016-04-18 08:35
@xiuie Duplicate issue of #289 

And with only 10% battery, I can't replicate it with iPhone 6 / iOS 9.3.1

**Comment by vysohanych** [comment] 2016-04-19 22:33
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Closed as completed** 2016-04-19 23:37 UTC
Labels: Duplicate
