### ISSUE TITLE
[1.9.53] iPhone 5/10.1.1 Validation message is not proper for entering wrong password. 

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#1097] opened 2016-12-07 11:19 UTC
Frequency: Always

1. Open application and Login with valid credential.
2. Tap on Setting and tap on "Forget password".
3. Enter current password, New password and Repeat password.
4. Tap on OK sign.
5. Again open setting and Forget password link and enter Old password in Current password tab and Current password in New and repeat password.
6. tap on Ok sign and verify page.

Expected result: Validation message should display for entering wrong password in Current password tab.

Actual result: Error "Unknown error" generated.

**Comment by testershub** [comment] 2016-12-07 11:31
@xiuie I can reproduce this issue for build [1.9.53] on iPhone 6 Plus / 10.1.1.

**Comment by hiteshbheda** [comment] 2016-12-08 19:03
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

Issue is resolved in build [2.1.0]

**Closed as completed** 2016-12-09 00:12 UTC
Labels: High (bug), Reproducible
