### ISSUE TITLE
[1.9.13] iPhone 6 Plus / 9.2.1 - Lomotif project doesn't get saved and not displayed on "Home" screen after export.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#638] opened 2016-08-26 11:39 UTC
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START >> Motif tab".
3: Search for motif category with single character.e.g. "X"
4: Select few motifs and proceed to "Create" screen without music.
5: Wait till processing.
6: Preview will be displayed.
7:  Export the lomotif and skip sharing.
8: Check if recently created lomotif project is not displayed on "Home" screen.

Expected result: Lomotif project should be saved and displayed on "Home" screen after export.

Actual result: Lomotif project doesn't get saved and not displayed on "Home" screen after export the lomotif.

**Comment by Dipamit** [comment] 2016-08-29 10:13
@xiuie : Not able to reproduce this issue on iPhone 5/9.3.4 for build 1.9.13

Connection : 3G

**Comment by testershub** [comment] 2016-08-29 12:00
@xiuie I can reproduce this issue for build [1.9.14] on iPhone 6S / 9.3.2.

**Comment by testershub** [comment] 2016-09-01 07:12
@xiuie I can reproduce this issue for build [1.9.16] on iPhone 6S / 9.3.2.

**Comment by hiteshbheda** [comment] 2016-09-01 09:19
@xiuie I can't reproduce this issue for build [1.9.16] on iPhone 6 / iOS 9.3.5

**Comment by hiteshbheda** [comment] 2016-12-11 06:28
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]

**Comment by testershub** [comment] 2016-12-12 05:47
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1.

**Closed as completed** 2016-12-12 06:31 UTC
Labels: High (bug), Reproducible
