### ISSUE TITLE
[1.8.16] iPhone 6 / iOS 9.3.1 - Application Crash - Try to play lomotif from Instagram Folder without selecting it

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#409] opened 2016-05-16 14:33 UTC
Frequency: Most of time

Action:
1. Launch Lomotif
2. Click on Start
3. Open Instagram folder
4.Click on Play button to play any lomotif without selecting it
5. Check whether application crash or not

Expected result: By clicking on Play button on lomotif, lomotif should be played

Actual result: Application crash

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UeW5OeFgyd3FtRUU)

![1](https://cloud.githubusercontent.com/assets/9691390/15292495/fafd2fa2-1ba0-11e6-9375-9a01435723ae.PNG)

![2](https://cloud.githubusercontent.com/assets/9691390/15292494/fad053d8-1ba0-11e6-9bbc-6d847cefa185.PNG)

**Comment by pallavipillai** [comment] 2016-05-17 07:20
The issue is reproducible for build [1.8.18]/iPAD 3/iOS 9.3.1

**Comment by hiteshbheda** [comment] 2016-05-18 18:59
@xiuie @tsukisa I can replicate the same issue for build [1.8.19] on iPhone 6 / iOS 9.3.1

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UZy0zcnhEaTlqVnc)

**Comment by tsukisa** [comment] 2016-05-19 22:21
@xiuie fixed with commit Lomotif/lomotif-ios@a99b2fed997774bbfe8f7d08124243234c8e4d58

**Closed as completed by tsukisa** 2016-05-19 22:21 UTC
Labels: Critical (bug)
