### ISSUE TITLE
[1.7.12] iPad Mini / iOS 8.3 - Settings - Application crashes when user taps Instagram button on Linked Accounts screen

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#245] opened 2016-03-25 16:38 UTC
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap Settings icon on the home screen
3. Tap Linked Accounts button on Settings screen
4. Tap Instagram button on the Linked Accounts screen

Expected result: User sees Instagram screen

Actual result: Application crashen

Video: [Recording #51.zip](https://github.com/Lomotif/lomotif-ios-issues/files/189750/Recording.51.zip)

crash log: [crash_log.txt.zip](https://github.com/Lomotif/lomotif-ios-issues/files/189747/crash_log.txt.zip)

Note: Seems it depends from bug #243 (Video 2)

**Comment by hiteshbheda** [comment] 2016-03-26 05:09
@xiuie @tsukisa @vysohanych I can't replicate it with iPhone 6 / iOS 9.3

Please check this attached video. It will help you what i get.

[Instagram Video](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UY0s1dW5XWjhzZ00)

**Comment by hiteshbheda** [comment] 2016-04-13 08:16
@xiuie @tsukisa I can't reproduce this issue on build [1.8.4] on iPhone 6 / 9.3.1

**Comment by 87Swati** [comment] 2016-04-19 13:57
i can reproduce the same issue on build [1.8.6] on IpadAir/9.3.1

**Comment by hiteshbheda** [comment] 2016-04-19 14:41
@xiuie @tsukisa I can't reproduce this issue for build [1.8.6] on iPhone 6 / iOS 9.3.1

**Comment by vysohanych** [comment] 2016-04-19 20:43
I can reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by hiteshbheda** [comment] 2016-04-20 05:44
@xiuie @tsukisa Can you please triage this issue? As i am unable to reproduce it but @vysohanych can replicate it every time.

**Comment by vysohanych** [comment] 2016-04-20 21:15
Yes I can reproduce it on build 1.8.7 on iPad 2 iOS 9.3.1. and iPad mini iOS 8.3

**Comment by tsukisa** [comment] 2016-04-20 21:46
@xiuie @vysohanych found out that is iPad issue only, fixed with commit Lomotif/lomotif-ios@edd8a8e02c3a757cb678ec56f168d6e4a4d78cd6

**Closed as completed by tsukisa** 2016-04-20 21:46 UTC
Labels: High (bug)

**Comment by hiteshbheda** [comment] 2016-04-21 04:26
@tsukisa Thanks..!! As i have tried to reproduce it multiple times but i was unable to make it possible on my iPhone 6. **Thanks for update as it's iPad issue only.**
