### ISSUE TITLE
[1.6.8] iPhone 6/9.1 - Problem in saving the movie

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#40] opened 2016-01-15 07:45 UTC
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select audio and video files
4. Tap right mark (save button) on top right corner
5. Tap on app home button
6. Click yes
7. In app home screen the movie recently created not shown
8. Now click setting button on same page
9. Click cross button
10. Now you will see the movie that has been recently created.

Whenever user creates a movie and saves it and go back to app home by clicking the app home button then click yes. In home screen you will not see the movie that has been created recently. Now click on the setting button and click cross button. Now the movie will appears on the home screen.

Expected Result: Movies should be added on home screen as saved by the user

Actual Result: The movie is not appearing in the home instantly after saving it.

**Comment by tsukisa** [comment] 2016-01-17 10:20
A duplicate of #32 
Fixed with commit Lomotif/lomotif-ios@e7f42ee80a3fad278ef45f32f16852b0924a8824

**Closed as completed by tsukisa** 2016-01-17 10:20 UTC
Labels: Duplicate
