### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2.1 - Facebook Messanger Unable to play shared Lomotif  - Bug on sharing lomotif to Facebook Messanger

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#199] opened 2016-03-05 13:57 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any pictures / video from Camera Roll
4. Select any song from My Music tab
5. Create Lomotif
6. Tap on export button, on top right corner
7. Select Facebook Messanger to share created lomotif
8. Select a contact from Messanger to share/send created lomotif
9. Send lomotif
10. After sent, click on play button to play shared lomotif

Expected: Shared Lomotif should be played after sharing on Facebook Messanger

Actual: Error - Unable to play shared lomotif in Facebook Messanger

![img_0848](https://cloud.githubusercontent.com/assets/9691390/13547891/4bf0de4e-e308-11e5-837e-986bf418856f.PNG)

**Comment by xiuie** [comment] 2016-03-12 02:46
Duplicate of #211

**Closed as completed** 2016-03-12 02:47 UTC
