### ISSUE TITLE
[1.9.39] iPhone 6 Plus / 10.1.1, iPhone 5S / 9.3.5 - Music is getting added to lomotif even when user doesn't add any music from "Find Music / My music" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#883] opened 2016-11-05 13:25 UTC
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select few motifs.
3: Tap on any song under "Find Music" tab (Music preview will starts playing).
4: Navigate back to "Camera roll / motifs" screen.
5: Tap on next option to proceed "Find Music" screen.
6: Observe the selected song in step-3 is displayed as deselected.
7: Proceed to "Create" screen.
8: Check if lomotif is created without any music.

Expected result: Warning message "Are you sure you want to proceed without adding music?" should be displayed when user proceeds to "Create" screen without selecting any music.

Actual result:  Music is getting added to lomotif even when user doesn't add any music from "Find Music / My music" tab.

**Comment by hiteshbheda** [comment] 2016-11-05 18:03
@xiuie Duplicate of #850

**Closed as completed** 2016-11-07 03:10 UTC
Labels: Duplicate
