### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - Instagram Issue - 2 Folders available for Instagram in Camera Roll

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#153] opened 2016-02-25 14:52 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Camera Roll on Albums screen
4. Check for Instagram

Expected result: Only one folder of Instagram should be available

Actual result: Shows 2 different folders for Instagram

![img_0776](https://cloud.githubusercontent.com/assets/9691390/13323013/7b803964-dbfd-11e5-9348-7eb9d0d9b0b6.PNG)

**Comment by tsukisa** [comment] 2016-03-18 13:32
duplicate of #193

**Closed as completed by tsukisa** 2016-03-18 13:32 UTC
Labels: Low (bug)
