### ISSUE TITLE
[1.9.53] iPhone 6 / 10.1.1- Error on changing password second time - Change password 2 times

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1105] opened 2016-12-07 17:06 UTC
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials
3. Go to User profile information page
4. Click on "Password" field to change Password
5. On next screen, enter current password and also enter valid new password and repeat password and click on Ok (tick)
6. Password will be changed
7. Again tap on "Password" field to change Password
8. Enter updated password (Enter password which is updated in step 5), and enter valid new password and repeat password
9. Check whether user is able to change Password second time or not

Expected result: User should be able to change Password multiple times

Actual result: 
1. Error message "Error-Unknown" display
2. User is only able to change password once, if tries second time to change password then displays Error popup

![img_2110](https://cloud.githubusercontent.com/assets/9691390/20978096/99ee5a46-bccd-11e6-8218-a73dcfa24f18.PNG)

**Comment by testershub** [comment] 2016-12-08 05:32
@xiuie Duplicate of #1097

**Comment by hiteshbheda** [comment] 2016-12-08 19:03
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

Issue is resolved in build [2.1.0]

**Closed as completed** 2016-12-09 00:12 UTC
