### ISSUE TITLE
[1.6.9] iPhone 6/9.1 - Application crashed when searching a song (Critical Bug)

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#48] opened 2016-01-16 06:55 UTC
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select video files
4. Click right button on top right corner
5. Now in song search any song i.e. birthday
6. Wait for 5 secs
7. Application crashed

When a user creates a movie and selects a video and in a song list he searches for a song. Application crashed

Expected Result: Application should not crash

Actual Result: App crashing all the time

**Comment by tsukisa** [comment] 2016-01-17 10:17
@ruiwen Found the issue, it was caused by id field is not an integer but a string value.

**Comment by ruiwen** [comment] 2016-01-17 10:23
Fixed with https://github.com/Lomotif/lomotif-music/commit/c59567cd4cf18d77b2266d5f718789a6c2e809cb

**Closed as completed** 2016-01-17 10:23 UTC
