### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - App Crash - When click on Playlists from Option/Menu button (Left to search music space) list

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#163] opened 2016-02-26 08:42 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Camera Roll on Albums screen
4. Select few photos from Camera Roll
5. Go to My Music tab
6. Click on Search bar
7. Search for particular word/string/character (I have used "Bhi" string)
8. Click on Option button (Left to search music space)
10. Select Playlists from given list

Expected result: Playlist / songs, contain "Bhi" (search word string), should be displayed

Actual result: Application crashes

![img_0782](https://cloud.githubusercontent.com/assets/9691390/13347308/f0f146bc-dc92-11e5-84ef-f606dfc3bea7.PNG)

![img_0783](https://cloud.githubusercontent.com/assets/9691390/13347309/f0f52976-dc92-11e5-96f7-2d4f2f5e4fc1.PNG)

![img_0784](https://cloud.githubusercontent.com/assets/9691390/13347310/f0f95b2c-dc92-11e5-9291-736ca9a11f0c.PNG)

**Comment by xiuie** [comment] 2016-02-26 09:14
I can't replicate this though..

**Comment by hiteshbheda** [comment] 2016-02-26 09:21
@xiuie I can replicate it every time

Please Go to your My Music tab and search for a word which is available in any song

Then try to follow mentioned steps. (I have tried it for word "Bhi" as shown in screenshot) So please try for a word which available in the song name

**Comment by hiteshbheda** [comment] 2016-02-26 12:48
@xiuie I just tried and replicate it again. App crash.
I'm not sure it happens to me only or to everyone.

**Comment by vysohanych** [comment] 2016-04-17 13:17
This bug seems is duplicate of bug #158 . You can close one of them.

**Comment by vysohanych** [comment] 2016-04-17 13:17
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Closed as completed** 2016-04-20 04:05 UTC
Labels: Duplicate
