### ISSUE TITLE
[1.8.33] iPhone 6 / iOS 9.3.2 - Song not added after "Music Change" process - Create lomotif and change music from it does not add new song

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#485] opened 2016-06-21 06:27 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start
3. Select few motifs and apply from top right corner
4. Now Tap on My Music category
5. Select any song and apply from top right corner
6. Scroll down the screen
7. At Bottom of the screen, tap on "Music change" icon
8. Don't select any song and click on Apply button
9. Observe whether song with waveform exist or not 

Expected result: When user click on "Change Music" icon and doesn't select any song should continue with previously added song

Actual result: Previously available Song not added in lomotif

**Comment by xiuie** [comment] 2016-06-23 08:24
@hiteshbheda I can't reproduce this anymore. Let me know if you can. Otherwise, closing.

**Closed as completed by xiuie** 2016-06-23 08:24 UTC

**Comment by hiteshbheda** [comment] 2016-06-23 09:19
@xiuie I can't reproduce this issue for build [1.8.34] on iPhone 6 / iOS 9.3.2
