### ISSUE TITLE
 [1.7.2] iPhone 6 / 9.2.1- Enable Filters  - App Crashing (if filters switch is enabled as files are still loading)

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#99] opened 2016-02-12 09:29 UTC
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select 50 screenshots
5. Select any song 
6. Once you enter the Create screen (while files are still loading), switch on Filters
7. App crash

Expected Result: Files load and filters are enabled

Actual Result: Lomotif app crashes

**Comment by tsukisa** [comment] 2016-02-15 08:00
Duplicate of #33

**Closed as completed by tsukisa** 2016-02-15 08:00 UTC
Labels: Critical (bug), Duplicate
