### ISSUE TITLE
[1.9.46] iPhone 6 / 10.1.1- Lomotif autosaves - Open existing lomotif, make changes and select "No" for not save lomotif changes

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1021] opened 2016-11-25 14:44 UTC
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials
3. Click on "In Progress" tab on user profile page
4. Load any existing lomotif
5. Change lomotif by adding new assets or applying any effects
6. Click on Home button 
7. Click on "NO" on "Would you like to save your changes?" popup
8. Check whether lomotif updates and autosaves or not

Expected result: When user select "NO" for not saving changes, then lomotif should not save automatically

Actual result: Lomotif autosaves even though user has selected "NO" on "Would you like to save your changes?" popup

IMPORTANT NOTE: Issue logged based on Xiuie's feedback

**Comment by testershub** [comment] 2016-11-28 05:27
@xiuie I can't reproduce this issue for build [1.9.47] on iPhone 6 Plus / 10.1.1 and iPhone 5S / 9.3.5.
Changes are discarded when user taps on "No" option on "Create" screen.

**Comment by xiuie** [comment] 2016-11-28 13:10
Yeah I think he fixed it for this build. I can't reproduce this issue for build [1.9.47] on iPhone 6S / 10.1.1. @hiteshbheda Can you verify on the latest build and let me know if I can close this?

**Comment by Dipamit** [comment] 2016-11-29 13:41
@xiuie: Not able to reproduce this issue on iPhone 5/10.1.1  for build 1.9.47

**Comment by hiteshbheda** [comment] 2016-11-29 13:45
@xiuie I can't reproduce it now. You can close it

**Closed as completed** 2016-12-01 04:50 UTC
Labels: Help Wanted, High (bug)
