### ISSUE TITLE
[1.7.10] iPhone 6 / 9.2.1 - App Crashes - Export lomotif by clicking on Close button

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#232] opened 2016-03-22 08:00 UTC
Frequency: Twice / Thrice

Action:
1. Launch Lomotif
2. Tap on START button
3. Select few Motifs from Motif tab
4. Add any song from Find Music
5. Save lomotif on local directory
6. Again start lomotif 
7. Open previously created lomotif
8. Add one more picture / video / motif
9. Apply filter value ON
10. Apply some text on the screen
10. Click on export button (Right top corner)
11. Click on Close button at top right corner of the screen

Expected result: Created lomotif should be saved to camera roll when clicked on Close button

Actual result: Application Crashes

**Comment by hiteshbheda** [comment] 2016-03-25 06:29
@xiuie I can't reproduce this issue in build [1.7.12] with iPhone 6 / iOS 9.3

I have tried this 3 - 4 times. No crashing.

**Comment by tsukisa** [comment] 2016-03-28 02:38
duplicate of #227

**Closed as completed by tsukisa** 2016-03-28 02:38 UTC
Labels: Low (bug)
