### ISSUE TITLE
[1.9.24] iPhone 6 Plus / 10.0.1 - Black screen is displayed at "Photo App" for lomotif which is created with "Motifs".  

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#758] opened 2016-09-23 08:19 UTC
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select few motifs from "Motifs" tab.
3: Skip the music and proceed to "Create" screen.
4: Enable "Sticker" toggle button and apply any sticker.
5: Enable "Filter" toggle button.
6: Enter title.
7: Tap on added assets and change the time frame position (Start position).
8: Export the lomotif.
9: Open photo app and play recently exported lomotif.
10: Check if black screen is displayed.

Expected result: Preview should be displayed when user play the lomotif in "Photo App".

Actual result: Black screen is displayed at "Photo App" when user play the recently exported lomotif.

Refer following video for more details:
http://www.screencast.com/t/3m8Qi1bor

**Comment by hiteshbheda** [comment] 2016-09-23 13:44
@xiuie I can reproduce this issue for build [1.9.24] on iPhone 6 / iOS 10.0.1

Frequency: 2/6

**Comment by hiteshbheda** [comment] 2016-12-11 06:11
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]

**Closed as completed** 2016-12-12 02:27 UTC
Labels: Low (bug), Reproducible

**Comment by testershub** [comment] 2016-12-12 05:34
@xiuie I can still reproducible this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1.
Black preview is displayed at "Photos" app.
