### ISSUE TITLE
[1.7.0] iPhone 6 / 9.2.1- App Crash - After sharing app to WhatsApp, app crash automatically

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#83] opened 2016-02-08 16:12 UTC
Frequency- Once

Action
1. Start
2. Select video from camera roll
3. Select any song
4. Create Lomotif
5. Tap on Export button and click on Yes
6. Select WhatsApp from Social Media sharing page
7. Send Created Lomotif on WhatsApp to any contact
8. Message sent successfully
9. Social Media sharing page appear
10. App crash

Expected result: App should not be crash
Actual result: App crach

**Comment by xiuie** [comment] 2016-02-09 03:11
I can replicate this @tsukisa twice. You must hit "x" to close the sharing page.

**Comment by tsukisa** [comment] 2016-02-15 06:28
Duplicate of #89

**Closed as completed by tsukisa** 2016-02-15 06:28 UTC
Labels: Duplicate
