### ISSUE TITLE
[1.8.26] iPad mini / iOS 8.3 - Export - 'Error - 3000' when user tries to export lomotif

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#452] opened 2016-05-27 08:03 UTC
Frequency: Every Time

Action:
1. Open the application
2. Tap START button on the home screen
3. Select some motifts on the Motif tab from the Albums screen
4. Tap apply button on the Albums screen
5. Select any song on the Find Music screen
6. Tap apply button on the Find Music screen
7. Tap export button on the Create screen

Expected result: Sharing screen appears after tapping the export button on the Create screen

Actual result: 'Error - 3000' appears after tapping the export button on the Create screen

Video: [Recording #47.mp4.zip](https://github.com/Lomotif/lomotif-ios-issues/files/286015/Recording.47.mp4.zip)

**Comment by hiteshbheda** [comment] 2016-05-27 08:07
I can't reproduce this issue for build [1.8.26] on iPhone 6 / iOS 9.3.2.

I am able to reach to Export screen and even able to export lomotif on certain media.

**Comment by Dipamit** [comment] 2016-05-27 12:53
Not able to reproduce this issue on iPhone 5/8.3 and iPhone 5/9.3.1 for build [1.8.26]

**Comment by tsukisa** [comment] 2016-05-27 21:16
fixed with commit Lomotif/lomotif-ios@7a1847260a28b749fc7302d3eb9003f5b8e17cfb

**Closed as completed by tsukisa** 2016-05-27 21:16 UTC
