### ISSUE TITLE
[1.7.3] iPhone 6 / 9.2.1 - Without any change in created lomotif, Stickers, Filters and Text appear - During attempting ON filters, Stickers and Text in created lomotif and not saving lomotif, automatically appears Stickers, Filters and Text

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#130] opened 2016-02-19 03:28 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Select and open any created lomotif
3. Select and ON the Stickers
4. Tap on Filters and ON it
5. Tap on Text button and enter any value for it.
6. Click on Home button
6. Select NO from "Would you like to save your changes?" window

Expected result: In existing Lomotif, Stickers, Filter and Text should not be appear

Actual result: Stickers, Filters and Text appear in saved lomotif even if we have not saved opened lomotif

**Comment by benchang** [comment] 2016-02-19 04:32
I can replicate this, basically we are saving the toggle settings for stickers/filters even when the user specifies not to

**Comment by tsukisa** [comment] 2016-03-18 13:21
duplicate of #125

**Closed as completed by tsukisa** 2016-03-18 13:21 UTC
Labels: Low (bug)
