### ISSUE TITLE
[1.7.10] iPhone 6 / 9.2.1 - App Crashes - During selection of Playlist option from My Music tab

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#228] opened 2016-03-21 15:32 UTC
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select few Motifs or photos
4. Select My Music tab
5. Click on Menu option (Left to search window)
6. Select Playlists option from the list

Expected result: Playlists songs should be displayed

Actual result: Application Crashes

![img_1014](https://cloud.githubusercontent.com/assets/9691390/13923879/4491c8c8-efa8-11e5-9e69-49977fb0c080.PNG)

**Comment by xiuie** [comment] 2016-03-21 16:13
Doesn't crash for me. I seem to remember this bug.. Is it because you don't have any playlists @hiteshbheda ?

**Comment by hiteshbheda** [comment] 2016-03-21 16:17
@xiuie I just tried it again and also created one new playlist. Still i replicate the same issue everytime and application crashes.

**Comment by tsukisa** [comment] 2016-03-22 05:58
@hiteshbheda @xiuie i suspect it is album art issue

**Comment by hiteshbheda** [comment] 2016-03-22 06:09
@tsukisa Should i add any album art for playlist?

**Comment by tsukisa** [comment] 2016-03-22 06:10
@hiteshbheda Nope it's ok. I will apply a fix for that to see if it really crashes on album art, it shouldn't crash without album art in the first place

**Comment by hiteshbheda** [comment] 2016-03-22 06:12
@tsukisa Ok. Thanks..!!!

Let me know if you need any help to replicate this issue anytime.

**Comment by Dipamit** [comment] 2016-03-22 18:19
I am able to reproduce this issue all time on iPhone 6 with 9.2 and iPhone 5 with 8.2. Attaching crash log hope it will help more to resolve this problem. 
[Lomotif Crash.zip](https://github.com/Lomotif/lomotif-ios-issues/files/184707/Lomotif.Crash.zip)

**Comment by hiteshbheda** [comment] 2016-03-25 06:50
@xiuie @tsukisa I can replicate this issue in build 1.7.12 with iPhone / iOS 9.3

Frequency: Every time

**Comment by vysohanych** [comment] 2016-04-13 11:56
I can't reproduce it on build 1.8.4 on iPad mini iOS 8.3

**Comment by hiteshbheda** [comment] 2016-04-13 15:08
@xiuie @tsukisa I can't reproduce it now for build [1.8.4] on iPhone 6 / iOS 9.3.1

**Comment by vysohanych** [comment] 2016-04-18 21:05
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1 . It's duplicate of bugs #206 and #163

**Closed as completed** 2016-04-20 03:55 UTC
Labels: Duplicate
